version: "3.9"

services:

  # Images built Dockerfile
  ng1:
    # build: .
    image: beorn/xpilot-servers
    # image: nixos/nix:latest
    # entrypoint: nix-shell -p xpilot-ng --run \
    # entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 2001 -clientPortStart 2000 -clientPortEnd 2999
    entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 15450 -clientPortStart 15451 -clientPortEnd 15469
    ports:
      - "15450-15469:15450-15469/udp"
    deploy:
      replicas: 1

  blood1:
    # build: .
    image: beorn/xpilot-servers
    # image: nixos/nix:latest
    # entrypoint: nix-shell -p bloodspilot-server --run \
    entrypoint: xpilots -reportMeta -contactPort 15550 -clientPortStart 15551 -clientPortEnd 15569
    ports:
      - "15550-15569:15550-15569/udp"
    deploy:
      replicas: 1

  # Alternative using auto-built images from nixery.dev
  blood2:
    image: nixery.dev/bloodspilot-server
    entrypoint: xpilots -reportMeta -contactPort 15650 -clientPortStart 15651 -clientPortEnd 15669
    ports:
      - "15650-15669:15650-15669/udp"
  ng2:
    image: nixery.dev/xpilot-ng
    entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 15750 -clientPortStart 15751 -clientPortEnd 15769
    ports:
      - "15750-15769:15750-15769/udp"

  # Entrypoint for easy debugging - docker compose run debug
  debug:
    image: nixery.dev/shell/xpilot-ng/bloodspilot-server
    profiles: ["debug"]
    entrypoint: sh -ls
