version: "3.9"

services:
  ng:
    # build: .
    image: beorn/xpilot-servers
    # image: nixos/nix:latest
    # entrypoint: nix-shell -p xpilot-ng --run \
    # entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 2001 -clientPortStart 2000 -clientPortEnd 2999
    entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 15345
    ports:
      - "15345"
    deploy:
      replicas: 1

  bloodspilot:
    # build: .
    image: beorn/xpilot-servers
    # image: nixos/nix:latest
    # entrypoint: nix-shell -p bloodspilot-server --run \
    entrypoint: xpilots -reportMeta -contactPort 15346
    ports:
      - "15346"
    deploy:
      replicas: 1
