version: "3.9"

services:
  ng:
    # build: .
    image: beorn/xpilot-servers
    # image: nixos/nix:latest
    # entrypoint: nix-shell -p xpilot-ng --run \
    # entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 2001 -clientPortStart 2000 -clientPortEnd 2999
    entrypoint: xpilot-ng-server -reportMeta -noQuit -contactPort 15450 -clientPortStart 15451 -clientPortEnd 15469
    ports:
      - "15450-15469:15450-15469/udp"
    deploy:
      replicas: 1

  bloodspilot:
    # build: .
    image: beorn/xpilot-servers
    # image: nixos/nix:latest
    # entrypoint: nix-shell -p bloodspilot-server --run \
    entrypoint: xpilots -reportMeta -contactPort 15550 -clientPortStart 15551 -clientPortEnd 15569
    ports:
      - "15550-15569:15550-15569/udp"
    deploy:
      replicas: 1
